name: BedWars1058-Addon-Platform
version: '1.0'
main: org.eu.cf3012.Bedwars1058_Platform.Bedwars1058_Platform
authors: [ chengfeng30121 ]
description: Bedwars1058 插件 - 救援平台
website: https://github.com/chengfeng30121/BedWars1058-Addon-Platform
depends: [ BedWars1058 ]
