name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk
      - name: Build
        run: |
          mvn --batch-mode --update-snapshots verify
          if [ -f "target/Bedwars1058-Platform.jar" ]; then
            echo "Build Success!"
          else
            echo "Build Failed!"
            exit 1
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: Release
          path: 'target/Bedwars1058-Platform.jar'
